FROM continuumio/miniconda3

# install python 3.8.5
RUN conda install python=3.9

RUN python -m pip install --upgrade pip==24.0

ADD requirements.txt /tmp/
RUN pip install -r /tmp/requirements.txt

RUN pip install "jax[cuda11_cudnn82]==0.4.7" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html

WORKDIR /usr/home/workspace
